//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Minyan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Minyan()
        {
            this.AsksToMinyans = new HashSet<AsksToMinyan>();
        }
    
        public long IdMinyan { get; set; }
        public long IdPrayer { get; set; }
        public System.DateTime DateMinyan { get; set; }
        public System.TimeSpan BeginningTimeNavToMinyan { get; set; }
        public long IdlocationMinyan { get; set; }
        public int NumOfPeopleInMinyan { get; set; }
        public bool SuccessfullyMinyan { get; set; }
    
        public virtual Prayer Prayer { get; set; }
        public virtual SafePointOnTheWay SafePointOnTheWay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsksToMinyan> AsksToMinyans { get; set; }
    }
}
